name: bikespace_dev
# run with 

services:
  bikespace_frontend:
    build:
      context: .
      dockerfile: docker/test/frontend.dockerfile
    environment:
      BIKESPACE_API_URL: http://localhost:8000/api/v2
      BIKESPACE_API_URL_DASHBOARD: http://localhost:8000/api/v2
    ports:
      - "8080:8080"
  bikespace_api:
    build:
      context: .
      dockerfile: docker/test/api.dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      APP_SETTINGS: "bikespace_api.config.DevelopmentConfig"
      DATABASE_URL: "postgresql://postgres:devpwd@db/bikespace_dev"
      FLASK_DEBUG: "true"
      FLASK_RUN_PORT: 8000
    ports:
    - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: bikespace_api/
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: "devpwd"
      POSTGRES_DB: "bikespace_dev"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10