"""create bikeparking_submissions table

Revision ID: 15b48eae3261
Revises:
Create Date: 2024-07-27 13:33:12.430320

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "15b48eae3261"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bikeparking_submissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "issues",
            postgresql.ARRAY(
                sa.Enum(
                    "NOT_PROVIDED",
                    "FULL",
                    "DAMAGED",
                    "ABANDONDED",
                    "OTHER",
                    name="issuetype",
                    native_enum=False,
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "parking_duration",
            sa.Enum(
                "MINUTES",
                "HOURS",
                "OVERNIGHT",
                "MULTIDAY",
                name="parkingduration",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("parking_time", sa.DateTime(), nullable=False),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bikeparking_submissions")
    # ### end Alembic commands ###
