"""add versioning to bikeparking_submissions

Revision ID: 28b74db16670
Revises: 35c211f42ad6
Create Date: 2025-10-27 20:07:47.719162

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "28b74db16670"
down_revision = "35c211f42ad6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bikeparking_submissions_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("latitude", sa.Float(), autoincrement=False, nullable=True),
        sa.Column("longitude", sa.Float(), autoincrement=False, nullable=True),
        sa.Column(
            "issues",
            postgresql.ARRAY(
                sa.Enum(
                    "NOT_PROVIDED",
                    "FULL",
                    "DAMAGED",
                    "ABANDONDED",
                    "OTHER",
                    name="issuetype",
                    native_enum=False,
                )
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "parking_duration",
            sa.Enum(
                "MINUTES",
                "HOURS",
                "OVERNIGHT",
                "MULTIDAY",
                name="parkingduration",
                native_enum=False,
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("parking_time", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("comments", sa.Text(), autoincrement=False, nullable=True),
        sa.Column(
            "submitted_datetime",
            sa.DateTime(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    with op.batch_alter_table(
        "bikeparking_submissions_version", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bikeparking_submissions_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_submissions_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_submissions_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    op.create_table(
        "transaction",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("remote_addr", sa.String(length=50), nullable=True),
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    with op.batch_alter_table(
        "bikeparking_submissions_version", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_submissions_version_transaction_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_submissions_version_operation_type")
        )
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_submissions_version_end_transaction_id")
        )

    op.drop_table("bikeparking_submissions_version")
    # ### end Alembic commands ###
