"""add bikeparking_submissions.test_column as example of migration with continuum enabled

Revision ID: 33037f517bd6
Revises: 8a772e570759
Create Date: 2025-11-16 11:33:28.128891

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33037f517bd6"
down_revision = "8a772e570759"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bikeparking_submissions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("test_column", sa.Text(), nullable=True))

    with op.batch_alter_table(
        "bikeparking_submissions_version", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column("test_column", sa.Text(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "bikeparking_submissions_version", schema=None
    ) as batch_op:
        batch_op.drop_column("test_column")

    with op.batch_alter_table("bikeparking_submissions", schema=None) as batch_op:
        batch_op.drop_column("test_column")

    # ### end Alembic commands ###
