"""set nullability (change to mapped columns)

Revision ID: 374da489d5d9
Revises: 8a772e570759
Create Date: 2026-05-03 12:25:18.706961

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "374da489d5d9"
down_revision = "8a772e570759"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=80), nullable=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "first_name", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "last_name", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column("active", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("active", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "last_name", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "first_name", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=80), nullable=True
        )

    # ### end Alembic commands ###
