"""make issues field required for submissions

Revision ID: 4467bcb63285
Revises: ab2ea390376d
Create Date: 2026-05-17 21:15:19.291164

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4467bcb63285"
down_revision = "ab2ea390376d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # backfill issues
    op.execute(
        sa.text("""
            UPDATE "bikeparking_submissions" 
            SET issues = '{OTHER}'
            WHERE issues IS NULL
       """)
    )

    # set issues to required
    with op.batch_alter_table("bikeparking_submissions", schema=None) as batch_op:
        batch_op.alter_column(
            "issues",
            existing_type=postgresql.ARRAY(sa.VARCHAR(length=12)),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bikeparking_submissions", schema=None) as batch_op:
        batch_op.alter_column(
            "issues",
            existing_type=postgresql.ARRAY(sa.VARCHAR(length=12)),
            nullable=True,
        )

    # ### end Alembic commands ###
