"""add submitted_datetime column

Revision ID: 51d48d2698e6
Revises: d950b6fcba82
Create Date: 2025-03-25 22:18:59.686247

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "51d48d2698e6"
down_revision = "d950b6fcba82"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bikeparking_submissions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("submitted_datetime", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bikeparking_submissions", schema=None) as batch_op:
        batch_op.drop_column("submitted_datetime")

    # ### end Alembic commands ###
