"""add Status, StatusUpdate, and SubmissionComment models

Revision ID: 5971ef830c0a
Revises: 8a772e570759
Create Date: 2025-12-23 19:18:55.934672

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5971ef830c0a"
down_revision = "8a772e570759"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bikeparking_comments_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("submission_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("status_update_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("comments", sa.String(), autoincrement=False, nullable=True),
        sa.Column(
            "submitted_datetime",
            sa.DateTime(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "moderation_status",
            sa.Enum(
                "FLAGGED",
                "HIDDEN",
                "BLOCKED",
                name="moderationstatus",
                native_enum=False,
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    with op.batch_alter_table("bikeparking_comments_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bikeparking_comments_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_comments_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_comments_version_status_update_id"),
            ["status_update_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_comments_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_comments_version_user_id"),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "bikeparking_status_updates_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("submission_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "status_id", sa.String(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "effective_datetime",
            sa.DateTime(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "submitted_datetime",
            sa.DateTime(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "moderation_status",
            sa.Enum(
                "FLAGGED",
                "HIDDEN",
                "BLOCKED",
                name="moderationstatus",
                native_enum=False,
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    with op.batch_alter_table(
        "bikeparking_status_updates_version", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bikeparking_status_updates_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_status_updates_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_status_updates_version_status_id"),
            ["status_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_status_updates_version_submission_id"),
            ["submission_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_status_updates_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_status_updates_version_user_id"),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "bikeparking_statuses",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column(
            "status_type",
            sa.Enum(
                "ACTION_REQUIRED",
                "RESOLUTION_PENDING",
                "RESOLVED_SUCCESS",
                "RESOLVED_INFORMATIONAL",
                "CLOSED_UNRESOLVED",
                "INVALID_SUBMISSION",
                name="statustype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("status_description", sa.String(), nullable=False),
        sa.Column("status_information", sa.String(), nullable=False),
        sa.Column("hide_by_default", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bikeparking_statuses_version",
        sa.Column("id", sa.String(length=256), autoincrement=False, nullable=False),
        sa.Column(
            "status_type",
            sa.Enum(
                "ACTION_REQUIRED",
                "RESOLUTION_PENDING",
                "RESOLVED_SUCCESS",
                "RESOLVED_INFORMATIONAL",
                "CLOSED_UNRESOLVED",
                "INVALID_SUBMISSION",
                name="statustype",
                native_enum=False,
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status_description", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "status_information", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column("hide_by_default", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    with op.batch_alter_table("bikeparking_statuses_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bikeparking_statuses_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_statuses_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_statuses_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    op.create_table(
        "bikeparking_status_updates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.String(length=256), nullable=False),
        sa.Column("effective_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "moderation_status",
            sa.Enum(
                "FLAGGED",
                "HIDDEN",
                "BLOCKED",
                name="moderationstatus",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["bikeparking_statuses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["bikeparking_submissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bikeparking_status_updates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bikeparking_status_updates_status_id"),
            ["status_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_status_updates_submission_id"),
            ["submission_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_status_updates_user_id"),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "bikeparking_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("status_update_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("comments", sa.String(), nullable=False),
        sa.Column("submitted_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "moderation_status",
            sa.Enum(
                "FLAGGED",
                "HIDDEN",
                "BLOCKED",
                name="moderationstatus",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["status_update_id"],
            ["bikeparking_status_updates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["bikeparking_submissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bikeparking_comments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bikeparking_comments_status_update_id"),
            ["status_update_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_comments_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bikeparking_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bikeparking_comments_user_id"))
        batch_op.drop_index(batch_op.f("ix_bikeparking_comments_status_update_id"))

    op.drop_table("bikeparking_comments")
    with op.batch_alter_table("bikeparking_status_updates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bikeparking_status_updates_user_id"))
        batch_op.drop_index(batch_op.f("ix_bikeparking_status_updates_submission_id"))
        batch_op.drop_index(batch_op.f("ix_bikeparking_status_updates_status_id"))

    op.drop_table("bikeparking_status_updates")
    with op.batch_alter_table("bikeparking_statuses_version", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_statuses_version_transaction_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_statuses_version_operation_type")
        )
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_statuses_version_end_transaction_id")
        )

    op.drop_table("bikeparking_statuses_version")
    op.drop_table("bikeparking_statuses")
    with op.batch_alter_table(
        "bikeparking_status_updates_version", schema=None
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bikeparking_status_updates_version_user_id"))
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_status_updates_version_transaction_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_status_updates_version_submission_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_status_updates_version_status_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_status_updates_version_operation_type")
        )
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_status_updates_version_end_transaction_id")
        )

    op.drop_table("bikeparking_status_updates_version")
    with op.batch_alter_table("bikeparking_comments_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bikeparking_comments_version_user_id"))
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_comments_version_transaction_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_comments_version_status_update_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_comments_version_operation_type")
        )
        batch_op.drop_index(
            batch_op.f("ix_bikeparking_comments_version_end_transaction_id")
        )

    op.drop_table("bikeparking_comments_version")
    # ### end Alembic commands ###
