"""change submitted_datetime to timezone-aware datetime

Revision ID: 7392d094ae76
Revises: 51d48d2698e6
Create Date: 2025-03-26 22:33:24.965370

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7392d094ae76"
down_revision = "51d48d2698e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bikeparking_submissions", schema=None) as batch_op:
        batch_op.alter_column(
            "submitted_datetime",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bikeparking_submissions", schema=None) as batch_op:
        batch_op.alter_column(
            "submitted_datetime",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
