"""add bikeparking_statuses table

Revision ID: 7d61cec05082
Revises: dea75e305cf6
Create Date: 2026-09-22 15:21:48.813287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d61cec05082'
down_revision = 'dea75e305cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikeparking_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_type', sa.String(), nullable=False),
    sa.Column('status_name', sa.Enum('ACTION_REQUIRED', 'RESOLUTION_PENDING', 'RESOLVED_SUCCESS', 'RESOLVED_INFORMATIONAL', 'CLOSED_UNRESOLVED', 'INVALID_SUBMISSION', name='statusname', native_enum=False), nullable=False),
    sa.Column('status_description', sa.Text(), nullable=False),
    sa.Column('hide_by_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_type')
    )
    op.create_table('bikeparking_statuses_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('status_type', sa.String(), autoincrement=False, nullable=True),
    sa.Column('status_name', sa.Enum('ACTION_REQUIRED', 'RESOLUTION_PENDING', 'RESOLVED_SUCCESS', 'RESOLVED_INFORMATIONAL', 'CLOSED_UNRESOLVED', 'INVALID_SUBMISSION', name='statusname', native_enum=False), autoincrement=False, nullable=True),
    sa.Column('status_description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('hide_by_default', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('bikeparking_statuses_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bikeparking_statuses_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bikeparking_statuses_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bikeparking_statuses_version_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikeparking_statuses_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bikeparking_statuses_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_bikeparking_statuses_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_bikeparking_statuses_version_end_transaction_id'))

    op.drop_table('bikeparking_statuses_version')
    op.drop_table('bikeparking_statuses')
    # ### end Alembic commands ###
