"""add flask plugin to sqlalchemy_continuum configuration

Revision ID: 8a772e570759
Revises: 28b74db16670
Create Date: 2025-10-27 20:50:41.864208

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a772e570759"
down_revision = "28b74db16670"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_transaction_user_id"), ["user_id"], unique=False
        )
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_transaction_user_id"))
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
