"""add optional user field for submissions

Revision ID: ab2ea390376d
Revises: ccc8dc32d22a
Create Date: 2026-05-14 19:59:42.337044

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab2ea390376d"
down_revision = "ccc8dc32d22a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bikeparking_submissions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_bikeparking_submissions_user_id"), ["user_id"], unique=False
        )
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])

    with op.batch_alter_table(
        "bikeparking_submissions_version", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.Integer(), autoincrement=False, nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_bikeparking_submissions_version_user_id"),
            ["user_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "bikeparking_submissions_version", schema=None
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bikeparking_submissions_version_user_id"))
        batch_op.drop_column("user_id")

    with op.batch_alter_table("bikeparking_submissions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_bikeparking_submissions_user_id"))
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
