"""add username to User and make First Name and Last Name optional

Revision ID: ccc8dc32d22a
Revises: 374da489d5d9
Create Date: 2026-05-14 14:42:22.433753

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ccc8dc32d22a"
down_revision = "374da489d5d9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # add username (nullable pre-backfill) and set first_name and last_name as optional
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("username", sa.String(length=255), nullable=True))
        batch_op.alter_column(
            "first_name", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "last_name", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    # backfill username
    # e.g. first_name="Test My", last_name="User", id=3 --> username=testmyuser3
    op.execute(
        sa.text("""
            UPDATE "user" 
            SET username = LOWER(REPLACE(
                CONCAT(first_name, last_name, id::text),
                ' ', ''
            ))
            WHERE username IS NULL
       """)
    )

    # set username to required (non-nullable)
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "username", existing_type=sa.String(length=255), nullable=False
        )
        batch_op.create_unique_constraint(None, ["username"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "last_name", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "first_name", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.drop_column("username")

    # ### end Alembic commands ###
