"""change parking_time to timezone-aware datetime

Revision ID: dea75e305cf6
Revises: 4467bcb63285
Create Date: 2026-08-23 14:37:36.875182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dea75e305cf6'
down_revision = '4467bcb63285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikeparking_submissions', schema=None) as batch_op:
        batch_op.alter_column('parking_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,)

    with op.batch_alter_table('bikeparking_submissions_version', schema=None) as batch_op:
        batch_op.alter_column('parking_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikeparking_submissions_version', schema=None) as batch_op:
        batch_op.alter_column('parking_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('bikeparking_submissions', schema=None) as batch_op:
        batch_op.alter_column('parking_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
