# supplemental compose to use with compose-prod.yaml for local testing
name: bikespace_prod

services:
  bikespace_api:
    environment:
      TRUSTED_PROXY_COUNT: ${TRUSTED_PROXY_COUNT:-1}

  reverse_proxy:
    ports:
      - "${CADDY_HTTP_PORT:-8002}:80"
