name: bikespace_prod

services:
  bikespace_api:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      APP_SETTINGS: "bikespace_api.config.ProductionConfig"
      DATABASE_URL: "postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_64_POSTGRES}@db/${POSTGRES_DB:-bikespace}"
      FLASK_DEBUG: "false"
      FLASK_RUN_PORT: 8000
      BIKESPACE_SECRET_KEY: ${SERVICE_PASSWORD_64_BIKESPACESECRETKEY}
      BIKESPACE_SECURITY_PASSWORD_SALT: ${SERVICE_PASSWORD_64_PASSWORDSALT}
      SEED_USER_EMAIL: ${SEED_USER_EMAIL:?}
      SEED_USER_PASSWORD: ${SERVICE_PASSWORD_64_SEEDUSERPASSWORD}
    ports:
      - 8000
    restart: always

  db:
    # Minimum version 18
    image: postgres:${POSTGRES_IMAGE_TAG:-latest}
    volumes:
      - "postgres_data:/var/lib/postgresql"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bikespace}
      POSTGRES_USER: ${SERVICE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_64_POSTGRES}
    healthcheck:
      test: pg_isready -h db -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    name: bikespace_postgres_data
