openapi: 3.0.0
info:
  version: 2.0.1
  title: BikeSpace API
  description: BikeSpace API

servers:
  - url: /api/v2
  - url: https://api-dev.bikespace.ca/api/v2

paths:
  /submissions:
    get:
      description: Returns a list of all the submitted answers
      parameters:
        - name: limit
          in: query
          description: Limits the number of items on a page
          schema:
            type: integer
        - name: offset
          in: query
          description: Specifies the page number of the submissions to be displayed
          schema:
            type: integer
      responses:
        "200":
          description: Successfully returned a list of submissions 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Submission'
            application/geo+json:
              schema:
                $ref: '#/components/schemas/Submission'
            text/csv:
              schema:
                $ref: '#/components/schemas/Submission'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      summary: Submit a new submission
      
      requestBody:
        description: Create a new submission
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Submission'
      responses:
        '201':
          description: Created
components:
  schemas:
    Submission:
      properties:
        id:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        issues:
          type: array
          items:
            type: string 
            enum:
              - not_provided
              - full
              - damaged
              - abandoned
              - other
        parking_duration:
          type: string
          enum:
            - minutes
            - hours
            - overnight
            - multiday
        parking_time:
          type: string
        comments:
          type: string
        submitted_datetime:
          type: string
          format: date-time
