openapi: 3.0.0
info:
  version: 2.0.2
  title: BikeSpace API
  description: BikeSpace API

servers:
  - url: /api/v2
  - url: https://api-dev.bikespace.ca/api/v2

paths:
  /submissions:
    get:
      description: Returns a list of all the submissions
      parameters:
        - name: limit
          in: query
          description: Limits the number of items on a page
          schema:
            type: integer
        - name: offset
          in: query
          description: Specifies the page number of the submissions to be displayed
          schema:
            type: integer
      responses:
        "200":
          description: Successfully returned a list of submissions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SubmissionOutputs"
            application/geo+json:
              schema:
                $ref: "#/components/schemas/SubmissionOutputs"
            text/csv:
              schema:
                $ref: "#/components/schemas/SubmissionOutputs"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      summary: Submit a new submission

      requestBody:
        description: Create a new submission
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubmissionInputs"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ["created"]
                  submission_id:
                    type: integer
                    minimum: 1

  /submissions/{submission_id}:
    get:
      description: Returns the specified submission
      parameters:
        - in: path
          name: submission_id
          required: true
          schema:
            type: string
          description: id of the submission to request
      responses:
        "200":
          description: Successfully returned a submission requested by id
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SubmissionOutputs"
                  - properties:
                      version_history_url:
                        type: string
                        format: uri
  /submissions/{submission_id}/history:
    get:
      description: Returns the edit history for the specified submission
      parameters:
        - in: path
          name: submission_id
          required: true
          schema:
            type: string
          description: id of the submission to request
      responses:
        "200":
          description: Successfully returned a submission edit history requested by id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SubmissionHistoryOutput"

components:
  schemas:
    SubmissionInputs:
      properties:
        latitude:
          type: number
          format: float
          example: 43.0
        longitude:
          type: number
          format: float
          example: -79.0
        issues:
          type: array
          items:
            type: string
            enum:
              - not_provided
              - full
              - damaged
              - abandoned
              - other
        parking_duration:
          type: string
          enum:
            - minutes
            - hours
            - overnight
            - multiday
        parking_time:
          type: string
          example: "2025-01-01 12:00:00"
        comments:
          type: string
    SubmissionOutputs:
      allOf:
        - properties:
            id:
              type: integer
              minimum: 1
        - $ref: "#/components/schemas/SubmissionInputs"
        - properties:
            submitted_datetime:
              type: string
              format: date-time
            version:
              type: integer
              minimum: 1
    SubmissionHistoryOutput:
      properties:
        version_index:
          type: number
          format: integer
          minimum: 1
        operation_type:
          type: number
          format: integer
          enum: [0, 1, 2]
          description: 0 = insert, 1 = update, 2 = delete
          example: 1
        changes:
          type: object
          example: { comments: ["original comment", "edited comment"] }
