name: bikespace_prodtest

services:
  bikespace_api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      APP_SETTINGS: "bikespace_api.config.ProductionConfig"
      DATABASE_URL: "postgresql://postgres:prodpwd@db/bikespace_prodtest"
      FLASK_DEBUG: "false"
      FLASK_RUN_PORT: 8000
    ports:
    - "8002:8000"
    develop:
      watch:
        - action: rebuild
          path: bikespace_api/
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: "prodpwd"
      POSTGRES_DB: "bikespace_prodtest"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10