# fly.toml app configuration file generated for bikespace-api-dev on 2025-06-05T21:40:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bikespace-api-dev'
primary_region = 'yyz'

[build]

[env]
  APP_SETTINGS = 'bikespace_api.config.ProductionConfig'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
