name: Test and Preview

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths:
      - bikespace_api/**
      - bikespace_frontend/**
      - .github/workflows/test-preview.yml

jobs:
  # variables are only available in workflow steps, so this config job is used to set shared config variables
  config:
    runs-on: ubuntu-latest
    outputs:
      python-version: "3.12.14"
      node-version: "24"
      postgres-image: postgres:15
    steps:
      - run: ":"

  apitest:
    name: API tests
    runs-on: ubuntu-latest
    needs: config
    env: &api_env
      BIKESPACE_SECURITY_PASSWORD_SALT: ${{ secrets.BIKESPACE_SECURITY_PASSWORD_SALT || 'fallback_salt_for_forked_prs' }}
      BIKESPACE_SECRET_KEY: ${{ secrets.BIKESPACE_SECRET_KEY || 'fallback_secret_key_for_forked_prs' }}
      SEED_USER_EMAIL: ${{ secrets.SEED_USER_EMAIL }}
      SEED_USER_PASSWORD: ${{ secrets.SEED_USER_PASSWORD }}
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres: &api_postgres_service # Docker Hub image
        image: ${{ needs.config.outputs.postgres-image }}
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ needs.config.outputs.python-version }}
          cache: "pip"
          cache-dependency-path: bikespace_api/requirements.txt
      - name: Run pytest
        run: make test-api
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          fail-on-error: false

  api-migration-test:
    name: Test if database migrations need to be generated for API
    runs-on: ubuntu-latest
    needs: config
    env: *api_env
    services:
      # Label used to access the service container
      postgres: *api_postgres_service
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ needs.config.outputs.python-version }}
          cache: "pip"
          cache-dependency-path: bikespace_api/requirements.txt
      - name: Run migration check
        run: make migrate-test-db

  test-frontend:
    name: Lint and Test Frontend
    runs-on: ubuntu-latest
    needs: config
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ needs.config.outputs.node-version }}
          cache: "npm"
          cache-dependency-path: bikespace_frontend/package-lock.json
      - name: Check code style
        run: make lint-frontend
      - name: Run Jest tests
        run: make test-frontend

  test-e2e:
    name: Frontend end-to-end tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: config
    env: *api_env
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres: *api_postgres_service
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ needs.config.outputs.node-version }}
          cache: "npm"
          cache-dependency-path: bikespace_frontend/package-lock.json
      - name: Install frontend dependencies
        run: cd bikespace_frontend && npm install
      - name: Get Playwright version
        id: playwright-version
        run: |
          echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./bikespace_frontend/node_modules/@playwright/test/package.json').version)")" >> $GITHUB_ENV
      - name: Cache Playwright browsers
        uses: actions/cache@v6
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright browsers and system dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: cd bikespace_frontend && npx playwright install --with-deps
      - name: Install Playwright system dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: cd bikespace_frontend && npx playwright install-deps
      - name: Run end to end tests
        run: cd bikespace_frontend && npx playwright test
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: bikespace_frontend/playwright-report/
          retention-days: 30

  publish:
    # Only publish previews for PRs from the same repository
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository}}
    name: Publish to Cloudflare Pages
    needs: [test-frontend, test-e2e, config]
    runs-on: ubuntu-latest
    env:
      MAPTILER_API_KEY: ${{ secrets.MAPTILER_API_KEY }}
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ needs.config.outputs.node-version }}
          cache: "npm"
          cache-dependency-path: bikespace_frontend/package-lock.json
      - name: Build static frontend
        run: make build-frontend
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy bikespace_frontend/out --project-name=bikespace-v2 --branch=${{ github.head_ref || github.ref_name }} --commit-dirty=true
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
